### ISSUE TITLE
Webex connection problems (proxy)

### ISSUE THREAD

**Issue by Fabianski-tr** [mattermost/mattermost-plugin-webex#16]
Hi,

I have installed this plugin but I have the following error connection:
```
We could not start a meeting.
Webex error: No Personal Room link found at XXXXX.webex.com for the room: ftizon
```

The webex site hostname and the room it's OK but I need a proxy for navigate to internet. 
it is possible to configure the plugin or connection to navigate through the proxy?

**Comment by levb** [comment]
This is an issue for all integrations, @lieut-data do you have an insight?

**Comment by lieut-data** [comment]
@Fabianski-tr, I believe that Go processes honour the `HTTP_PROXY` and `HTTPS_PROXY` environment variables. Link previews in Mattermost, for example, which now route through the server, require the same configuration.

Do you already have a proxy configuration in place for the Mattermost server? If not, I suspect you can just define these environment variables when you start up your Mattermost server and they /should/ take effect for plugins as well. Please let us know if that works!

**Comment by Fabianski-tr** [comment]
Hi! Yes, it works!

I added the environment variables in the mattermost.service file and it worked on the first one.
Info: https://docs.mattermost.com/install/outbound-proxy.html 

![imagen](https://user-images.githubusercontent.com/21104560/69314753-34642600-0c35-11ea-8dda-addc8f66433d.png)

Thank you so much @lieut-data , best regards!

**Comment by bbodenmiller** [comment]
Looks like GitLab Mattermost users can do this using https://docs.gitlab.com/omnibus/gitlab-mattermost/#setting-custom-environment-variables
