### ISSUE TITLE
Add plugin-specific support for outgoing HTTP proxy

### ISSUE THREAD

**Issue by bbodenmiller** [mattermost/mattermost-plugin-webex#23]
Many Mattermost instances do not want to or cannot enable system wide access to outside internet. This plugin should support accessing Webex site via a proxy.

**Comment by cpoile** [comment]
@bbodenmiller Could you give an example of how this works in your organization so we can evaluate the work required to add it? Thanks!

**Comment by bbodenmiller** [comment]
Our servers aren't allowed to connect to external URLs without going
through a proxy. I don't want to set the proxy for all of the sever or
Mattermost application (via env variable) but rather just for this plugin
to use.

**Comment by levb** [comment]
@bbodenmiller This is not a per-plugin solution, but you can set the `HTTP_PROXY` environment variable for the parent mattermost server process, and the plugins will use it.

https://golang.org/pkg/net/http/#ProxyFromEnvironment

**Comment by bbodenmiller** [comment]
@levb this isn't allowed in my scenario and exactly what I said I don't want to do!

**Comment by levb** [comment]
Ok, so the we'd need to introduce a new config key, and set the http client accordingly. I'll edit the description with more details, and make it a help wanted ticket. @bbodenmiller apologies for my misunderstanding.

**Comment by bbodenmiller** [comment]
@levb all good, thanks for helping. :)

**Comment by cpoile** [comment]
@bbodenmiller when #22 is completed, we won't need proxy support for the Webex plugin. But we would want it for other plugins (as a per-plugin config option).

**Comment by cpoile** [comment]
Because this isn't Webex specific, I'm moving the request to a ticket in Jira: https://mattermost.atlassian.net/browse/MM-22565
