### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by bbodenmiller** [mattermost/mattermost-plugin-webex#28]
Even with proxy set, I can't get this plugin working. The best the logs will tell me is that a room cannot be found. I set my room manually and it still doesn't work.

What URLs is the plugin hitting so I can try to do what it's doing manually and see if that works?

**Comment by cpoile** [comment]
Hi @bbodenmiller, to help diagnose this problem, can DM me the result of `/webex info`? (on community.mattermost.com I am `@christopher.poile`)

**Comment by cpoile** [comment]
Talking with @bbodenmiller on community.mattermost.com, so closing this ticket for now.

**Comment by bbodenmiller** [comment]
@cpoile sounds like person rooms are not enabled in our instance so we'd need something like the meet now option.
