### ISSUE TITLE
Use different URL to achieve linux compatibility

### ISSUE THREAD

**Issue by Centzilius** [mattermost/mattermost-plugin-webex#31]
Hi,
when using a linux browser webex throws the following error on /join and /start urls:
```
Sie können dieses Webex-Meeting nicht starten bzw. ihm beitreten, weil es für Webex Meetings-Videokonferenzen aktiviert ist. Diese Funktion wird von Ihrem Browser, Ihrer Browserversion oder Ihrem Betriebssystem nicht unterstützt. Wenden Sie sich an Ihren Administrator, um weitere Informationen zu erhalten.
```
Which is translated something like this:
```
You cannot start or join this Webex meeting because it is enabled for Webex meetings video conferencing. This feature is not supported by your browser, browser version, or operating system. Contact your administrator for more information.
```
How about we post links like this https://site.webex.com/meet/room_name that should work also on linux.

Kind regards,
Centzilius

**Comment by atisne** [comment]
No error to use `/join` (from Linux) for me.
But I have the reported error using `/start`. (Tested with Firefox 78.9 and Chrome 88.0)
It seems ok to use `/meet`.

**Comment by DHaussermann** [comment]
FWIW I can reproduce this on Ubuntu 20.04 running Chrome `83.0.4103.97`

![WebEx](https://user-images.githubusercontent.com/35588783/120042361-ef624200-bfd7-11eb-9b6d-b3883e4abb85.png)
