### ISSUE TITLE
Add codecov.io webhook to repo

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-webex#35]
Add codecov to a repo, codecov.io/gh/mattermost/mattermost-plugin-webex/settings and Create New Github Webhook. This will trigger the codecov webhook generation in github. The new webhook can be seen immediately in github webhooks, found under settings > webhooks

A badge will be added to the readme in a separate PR. https://github.com/mattermost/mattermost-plugin-webex/pull/36

**Comment by jfrerich** [comment]
closing. This was incorrect. To add codecov to a repo, https://codecov.io/gh/mattermost/mattermost-plugin-webex/settings and Create New Github Webhook. This will trigger the codecov webhook generation in github. The new webhook can be seen immediately in github webhooks.

**Comment by mickmister** [comment]
I see this when going to https://codecov.io/gh/mattermost/mattermost-plugin-webex/settings
![image](https://user-images.githubusercontent.com/6913320/86379087-61ab9480-bc58-11ea-9e1b-2157b658ab29.png)


Does this mean there is already codecov set up? It looks like there was a comment from codecov on this PR https://github.com/mattermost/mattermost-plugin-webex/pull/40 , but it says `No coverage uploaded for pull request base`

**Comment by jfrerich** [comment]
In the github repo, under `Settings` > `webhooks`, do you see the webhook for codecov?

**Comment by mickmister** [comment]
@hanzei Do you have any thoughts on this? I want to try removing the project from codecov so it can retry creating the webhook again.

![image](https://user-images.githubusercontent.com/6913320/86658180-d82cf700-bfb6-11ea-9eb1-096f506671c7.png)

![image](https://user-images.githubusercontent.com/6913320/86658237-e418b900-bfb6-11ea-8513-9b2f7afac692.png)

**Comment by hanzei** [comment]
Yeah, I would try deleting and re-creating the webhook.

**Comment by mickmister** [comment]
@hanzei Codecov doesn't let me delete the webhook though. It just shows this message here:

![image](https://user-images.githubusercontent.com/6913320/87236457-f3817300-c3b7-11ea-84dc-d3c1d24ccc88.png)

I have tried manually deleting the webhook in GitHub and setting it up manually GitHub, but this didn't solve anything. I'm trying to delete the project in codecov to have it recreate the project/webhook, but it's not letting me do that because I don't have admin rights in codecov.

**Comment by mickmister** [comment]
@jfrerich Looks like this is working for PR https://github.com/mattermost/mattermost-plugin-webex/pull/41 , and the shields in the README seem to be working. Can we close this ticket?

**Comment by jfrerich** [comment]
Looks good and can be closed!  What was the necessary action to fix the issue?

**Comment by mickmister** [comment]
@jfrerich I'm not sure, it may have been nothing. The webhook in the GitHub settings still says the webhook is failing, but it is working 🤷
