### ISSUE TITLE
Add slash command autocomplete functionality

### ISSUE THREAD

**Issue by iomodo** [mattermost/mattermost-plugin-webex#37]
From 5.24 MM server has a slash command autocomplete functionality feature. An API can be found [here](https://github.com/mattermost/mattermost-server/blob/master/model/command_autocomplete.go#L28)
To implement the feature add `AutocompleteData` struct to the `Command` when registering a slash command.

Similar PRs:
For Todo plugin https://github.com/mattermost/mattermost-plugin-todo/pull/69
For Agenda plugin https://github.com/mattermost/mattermost-plugin-agenda/pull/40

**Comment by GodlikePenguin** [comment]
I'll take a look at this

**Comment by GodlikePenguin** [comment]
There is a slight problem with how autocomplete works vs the way the plugin is set up, as there are both subcommands (e.g. `/webex info`) and argument based commands (e.g. `/webex <room id>`). The validation for the AutoComplete data does not allow arguments and subcommands on the same object:
```
 {"level":"error","ts":1602099366.5361428,"caller":"mlog/log.go:190","msg":"Unable to activate plugin","plugin_id":"com.mattermost.webex","error":"OnActivate: failed to register command: invalid autocomplete data in command: Command can't have arguments and subcommands"}
```

I can raise a PR for adding autocomplete to the Webex subcommands and if you have a suggestion on how best to deal with the two other commands I can address that too.

**Comment by iomodo** [comment]
Great question @GodlikePenguin. I'd suggest adding an alias just for autocomplete like `/webex room <room id>`, which will do same as `/webex <room id>`

**Comment by GodlikePenguin** [comment]
As a heads up in my PR I used `/webex join <room id>` rather than `/webex room` as `room` already had a command associated with it.
