### ISSUE TITLE
Is Webex on-premise supported?

### ISSUE THREAD

**Issue by rg-artcom** [mattermost/mattermost-plugin-webex#55]
Does the plugin support a local webex server installation (no cloud)? I can not see any information about it in the readme but I know the on-premise is different from the cloud webex.

**Comment by cpoile** [comment]
At the moment no, it only supports the cloud version of webex.

**Comment by cpoile** [comment]
@rg-artcom At the moment no, it only supports the cloud version of webex.

**Comment by rg-artcom** [comment]
May be you can add a note to the readme.md.
Thanks.
